FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache --virtual .build-deps python3 make g++ \
  && npm install -g nodemon \
  && apk del .build-deps

COPY package.json ./
RUN npm install

COPY . .

EXPOSE 5000

CMD ["nodemon", "-L", "src/server.js"]
